name: Release
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

permissions:
  contents: read  # for checkout

jobs:
  release:
    name: Release
    permissions:
      contents: write  # to be able to publish a GitHub release
      issues: write  # to be able to comment on released issues
      pull-requests: write  # to be able to comment on released pull requests
      id-token: write  # to enable use of OIDC for npm provenance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: docker://ghcr.io/cmgrayb/semantic-release -r ${{ github.repositoryUrl }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
